// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbbuyihuclndfcgwugjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYnV5aWh1Y2xuZGZjZ3d1Z2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjYzODQsImV4cCI6MjA3MDE0MjM4NH0.EPZAreCFArQ3SR8EQDZytF-Boo4GOgihBD4ZS6ScoCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});